apiVersion: v1
kind: Service
metadata:
  name: account-mysql
  labels:
    app: mysql
    service: account
spec:
  selector:
    app: mysql
    service: account
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP