apiVersion: v1
kind: Service
metadata:
  name: account
  labels:
    service: account
spec:
  selector:
    service: account
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP